### ISSUE TITLE
Want to work on contact us feature

### ISSUE THREAD

**Issue by Vijay-Gunwant** [OpenCodeEra/first-contribution#10]
I want to build the contact us feature ,I am planning to make the mail open with the desired destination email address . Plese provide me with the email address where people are to contact us.

**Comment by Vijay-Gunwant** [comment]
@AdarshRawat1 i am willing to work on this issue

**Comment by AKACHI-4** [comment]
hey @Vijay-Gunwant .. great u can start working on it.. also mention issue while making a related pr

**Comment by Vijay-Gunwant** [comment]
@AKACHI-4 hey thanks but i added a feature already regarding the Contact us feature in my last pull request  #9

**Comment by AKACHI-4** [comment]
oky ... Got it.. Thanks for u r contribution... 

don't forget to add urself in `data/Contributors.js` and `Contributors.md`
