### ISSUE TITLE
Link the hyper link in the footer with an actual link GDSC GEU page or fix this linkage

### ISSUE THREAD

**Issue by tmsagarofficial** [OpenCodeEra/first-contribution#14]
With respect to the above title of this issue, I would like to point out that in the footer section of the website the hyperlink with the text `GDSC DEU` isn't actually linked anywhere...

as shown in the below images
![image](https://github.com/OpenCodeEra/First-Contribution/assets/110724849/ae8ca7a3-65bc-4a0c-9424-46c546a210ea)
![image](https://github.com/OpenCodeEra/First-Contribution/assets/110724849/127ef240-edad-4143-8529-fcd41ea07262)

I would like to work on a fix for this issue once assigned to me. Pls let me know regarding the same

**Comment by AdarshRawat1** [comment]
> With respect to the above title of this issue, I would like to point out that in the footer section of the website the hyperlink with the text `GDSC DEU` isn't actually linked anywhere...

GDSC GEU *

@tmsagarofficial , please proceed.

**Comment by Ayush5042** [comment]
hello sir I would like to contribute on this issue please allow me

**Comment by AdarshRawat1** [comment]
@Ayush5042 Currently @tmsagarofficial is working on this issue. Please explore other issues listed in issues section or create a new issue (feature request / Bug report) and mention that you want to implement/fix  it.

**Comment by tmsagarofficial** [comment]
@AdarshRawat1 You want that hyperlink in the footer to redirect to the following site if I'm not wrong right?
1) https://gdsc.community.dev/graphic-era-dehradun/
or
2) https://dscgeu.vercel.app

**Comment by AdarshRawat1** [comment]
> 2) https://dscgeu.vercel.app

This one !

**Comment by tmsagarofficial** [comment]
Thanks for the clarification. Will start working on it. 🚀

**Comment by tmsagarofficial** [comment]
Pls check and merge my PR @AdarshRawat1 😅
